DROP TABLE IF EXISTS ADDRESSES;
CREATE TABLE ADDRESSES (
    id LONG AUTO_INCREMENT PRIMARY KEY,
    country VARCHAR(250) NOT NULL,
    lng FLOAT NOT NULL,
    lat FLOAT NOT NULL
);

DROP TABLE IF EXISTS COMPANIES;
CREATE TABLE COMPANIES (
   id LONG AUTO_INCREMENT PRIMARY KEY,
   company_name VARCHAR(250) NOT NULL,
   company_size VARCHAR(250) NOT NULL,
   address_id LONG,
   website VARCHAR(250),
   CONSTRAINT FK_AddressId FOREIGN KEY (address_id) REFERENCES ADDRESSES(id)
);



