create sequence hibernate_sequence start with 1 increment by 1
create table addresses (id bigint generated by default as identity, country varchar(255), lat float not null, lng float not null, primary key (id))
create table companies (id bigint generated by default as identity, company_name varchar(255), company_size varchar(255), website varchar(255), address_id bigint, primary key (id))
create table offers (id bigint not null, description varchar(255), title varchar(255), primary key (id))
alter table companies add constraint FK8w70yf6urddd0ky7ev90okenf foreign key (address_id) references addresses
create sequence hibernate_sequence start with 1 increment by 1
create table addresses (id bigint generated by default as identity, country varchar(255), lat float not null, lng float not null, primary key (id))
create table companies (id bigint generated by default as identity, company_name varchar(255), company_size varchar(255), website varchar(255), address_id bigint, primary key (id))
create table offers (id bigint not null, description varchar(255), title varchar(255), primary key (id))
alter table companies add constraint FK8w70yf6urddd0ky7ev90okenf foreign key (address_id) references addresses
create sequence hibernate_sequence start with 1 increment by 1
create table addresses (id bigint generated by default as identity, country varchar(255), lat float not null, lng float not null, primary key (id))
create table companies (id bigint generated by default as identity, company_name varchar(255), company_size varchar(255), website varchar(255), address_id bigint, primary key (id))
create table offers (id bigint not null, description varchar(255), title varchar(255), primary key (id))
alter table companies add constraint FK8w70yf6urddd0ky7ev90okenf foreign key (address_id) references addresses
